services:
  php5:
    build:
      context: ./
      dockerfile: ./.docker/php5/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:z
    working_dir: /var/www/html

  db:
    build:
      context: ./
      dockerfile: ./.docker/mysql/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .docker/mysql/my.cnf:/etc/mysql/my.cnf
